export * from "./about-footer"
export * from "./favorite-body"
export * from "./favorite-header"
export * from "./header"
export * from "./mobile-view"
export * from "./page-header"
export * from "./pc-view"
