name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - release

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: release

    permissions:
      contents: write

    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'changeset-release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.email "kazuking.1911@gmail.com"
          git config --global user.name "108yen"

      - name: Create GitHub Release
        uses: 108yen/changeset-release@v1
        with:
          target: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge branch
        run: |
          git switch main
          git merge release
          git push
